---
title: "Country Level Food Insecurity Trends"
author: "RBD RAM"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.width=15, fig.height=8)

library(readxl)
library(tidyverse)
library(plotly)
library(extrafont)
library(flextable)
library(officer)
library(rvg)
library(here)

#how to add template?
#change size / layouts of graphics so that fits better
#shorten code 

#create theme
#make x and y axis blank, put legend in bottom
theme_vamgraphs <- function(){ 
  font <- "Open Sans"   #assign font family up front
  theme_minimal() %+replace%    #replace elements we want to change
    theme(
      plot.title = element_text(family = "Open Sans SemiBold", color = "black", hjust = 0.5, size = 18, margin=margin(0,0,5,0)),
      plot.subtitle = element_text(family = "Open Sans SemiBold", color = "black", hjust = 0.5, size = 12, margin=margin(0,0,30,0)),
      strip.text = element_text(family = "Open Sans SemiBold", color = "black",  size = 10, margin=margin(0,0,30,0)),
      strip.text.x = element_text(family = "Open Sans SemiBold", color = "black",  size = 10, margin=margin(0,0,30,0)),
      #grid elements
      panel.grid.major = element_blank(),    #strip major gridlines
      panel.grid.minor = element_blank(),    #strip minor gridlines
      axis.ticks = element_blank(),          #strip axis ticks
      axis.text.x = element_text(family = "Open Sans", color = "black", size = 8, angle = 90),
      axis.title.x = element_blank(),
      axis.text.y =  element_blank(),
      legend.position = "bottom",
      legend.title = element_blank(),
      legend.text = element_text(family = "Open Sans SemiBold", color = "black", size = 8),
      panel.spacing = unit(1, "cm"),
      panel.margin = unit(2, "lines"),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank())
}

setwd("C:/RBD_CHIPC_dataprocessing/analysis/powerpoint/trends_adm0")


#import CH/IPC country level data
data <- read_excel("C:/RBD_CHIPC_dataprocessing/data/fiche_comm/adm0_fiche_comm.xlsx")
#only select data since 2017 and only the relevant exercise/reference period 
data_filtered <- data %>% filter(reference_year >= 2017) %>% filter(usethisperiod == "Y")
#use filter to only select proper exercise/reference periods (i.e. dont use the projections from Sep-Dec when Jan-May results are available the same year)
data_filtered <- data_filtered %>% filter(usethisperiod == "Y")
#abbreviate name of CAR so it fits graphics
data_filtered <- data_filtered %>% mutate(adm0_name = case_when(
  adm0_name == "Central African Republic" ~ "C.A.R.",
  TRUE ~ adm0_name))
#change reference time period labels to be more informative and not franglais
data_filtered <- data_filtered %>% mutate(reference_label = case_when(
  reference_label == "Jun-Aug" ~ "Projected: June-August",
  reference_label == "Sep-Dec" ~ "Current: September-December",
  reference_label == "Jan-May" ~ "Current: January-May"
))

#create % food insecure (phase3-5) out of analyzed population total
data_filtered <- data_filtered %>% mutate_at(vars(phase1:phase35), ~replace_na(., 0)) %>% mutate(perc35 = round((phase35 / population)*100,1),
                                          phase1million = phase1 / 1E6,
                                          phase2million = phase2 / 1E6,
                                          phase3million = phase3 / 1E6,
                                          phase4million = phase4 / 1E6,
                                          phase5million = phase5 / 1E6,
                                          phase35million = phase35 / 1E6) 
#make reference year a factor
data_filtered <- data_filtered %>% mutate(reference_year = as.factor(reference_year))
#creates list of sahel+NGA/CMR/CAR and coastal countries
sahelplus <- c("Burkina Faso","C.A.R.","Cameroon","Chad","Mali","Mauritania","Niger","Nigeria","Senegal")
coastal <- c("Benin","Cabo Verde","Cote d'Ivoire","Gambia","Guinea", "Ghana","Guinea-Bissau","Liberia","Sierra Leone","Togo")

#summarize phases for RBD 
data_filtered_rbd <- data_filtered %>% group_by (reference_label, reference_year) %>% 
summarise(phase1 = sum(phase1million), phase2 = sum(phase2million), phase3 = sum(phase3million), phase4 = sum(phase4million), phase5 = sum(phase5million), phase35 = sum(phase35million)) %>% ungroup()
data_filtered_rbd$reference_label <- as.factor(data_filtered_rbd$reference_label)
data_filtered_rbd$reference_label <- fct_relevel(data_filtered_rbd$reference_label, "Current: January-May", "Projected: June-August", "Current: September-December")
#pivot longer
data_filtered_rbd_all <- data_filtered_rbd %>% select(-phase35, -phase1) %>% pivot_longer(!reference_label:reference_year, names_to = "phase", values_to = "value")
#create another variable not showing less than 0.1
data_filtered_rbd_all <- data_filtered_rbd_all %>% mutate(value_filtered = replace(value, value<0.1, NA)) %>% mutate(value_filtered = round(value_filtered,1))

#summarized phases for each country in RBD
data_filtered_country <- data_filtered %>% group_by(reference_label, reference_year, adm0_name) %>% 
  summarise(phase1 = sum(phase1million), phase2 = sum(phase2million), phase3 = sum(phase3million), phase4 = sum(phase4million), phase5 = sum(phase5million), phase35 = sum(phase35million)) %>% ungroup()
#pivot longer
data_filtered_country <- data_filtered_country %>% select(-phase35,-phase1) %>% pivot_longer(!reference_label:adm0_name, names_to = "phase", values_to = "value")
#CH color code
CH_colors = c("phase1" = "#c6ffc7", "phase2" = "#ffe718", "phase3" = "#e88400", "phase4" = "#e02d00", "phase5" = "#5e0803")

#Entire region
#number phase3-5 projected
plot_rbd_35 <- data_filtered_rbd %>%  ggplot(aes(x = reference_year, y = phase35)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ reference_label) +theme_vamgraphs() +labs(title = "Trends of the Number of Food Insecure (phase 3 - 5) by Season", subtitle = "Includes all RBD Countries", caption = "") 
plot_rbd_35  <- plot_rbd_35  +ylab("number of people (millions) in phase3-5") +geom_text(aes(label = round(phase35,1), angle = 90, vjust = .5, hjust = -.1), size = 3) 
#number by phase - faceted by phase
#projected
plot_rbd_proj <- data_filtered_rbd_all %>% filter(reference_label == "Projected: June-August") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year", subtitle = "June - August, 2017 - 2021, Includes all RBD Countries", caption = "") 
plot_rbd_proj  <- plot_rbd_proj +ylab("number of people (millions)")  +geom_text(aes(label = value_filtered, angle = 0), size = 3) 
#janmay
plot_rbd_janmay <- data_filtered_rbd_all %>% filter(reference_label == "Current: January-May") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity")  +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year", subtitle = "January - May, 2017 - 2021, Includes all RBD Countries", caption = "") 
plot_rbd_janmay  <- plot_rbd_janmay +ylab("number of people (millions)")   +geom_text(aes(label = value_filtered, angle = 0), size = 3) 
#sepdec
plot_rbd_sepdec <- data_filtered_rbd_all %>% filter(reference_label == "Current: September-December") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year", subtitle = "September-December, 2017 - 2021, Includes all RBD Countries", caption = "") 
plot_rbd_sepdec  <- plot_rbd_sepdec +ylab("number of people (millions)")   +geom_text(aes(label = value_filtered, angle = 0), size = 3) 
#number by phase - faceted by phase
#projected
plot_rbd_proj_fac <- data_filtered_rbd_all %>% filter(reference_label == "Projected: June-August") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ phase) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Populations by Phase and Year", subtitle = "June - August, 2017 - 2021, Including all RBD Countries", caption = "") 
plot_rbd_proj_fac  <- plot_rbd_proj_fac +ylab("number of people (millions)")+geom_text(aes(label = round(value,1), angle = 90, vjust = .5, hjust = -.1), size = 3) 
#janmay
plot_rbd_janmay_fac <- data_filtered_rbd_all %>% filter(reference_label == "Current: January-May") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ phase) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Populations by Phase and Year", subtitle = "January - May, 2017 - 2021, Including all RBD Countries", caption = "") 
plot_rbd_janmay_fac  <- plot_rbd_janmay_fac +ylab("number of people (millions)") +geom_text(aes(label = round(value,1), angle = 90, vjust = .5, hjust = -.1), size = 3)  
#sepdec
plot_rbd_sepdec_fac <- data_filtered_rbd_all %>% filter(reference_label == "Current: September-December") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ phase) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Populations by Phase and Year", subtitle = "September-December, 2017 - 2021, Including all RBD Countries", caption = "")
plot_rbd_sepdec_fac  <- plot_rbd_sepdec_fac +ylab("number of people (millions)") +geom_text(aes(label = round(value,1), angle = 90, vjust = .5, hjust = -.1), size = 3)  


#Sahel
#number phase3-5 projected
plot_sahel_proj <- data_filtered %>% filter(adm0_name %in% sahelplus & reference_label == "Projected: June-August")  %>%
  ggplot(aes(x = reference_year, y = phase35million)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends of the Number of Food Insecure (phase3 to phase5)", subtitle = "June - August, 2017 - 2021: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_proj <- plot_sahel_proj  +ylab("number of people (millions) in phase3-5") +geom_text(aes(label = round(phase35million,1), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 14)) 
#number phase3-5 current - Jan-May
plot_sahel_janmay <- data_filtered %>% filter(adm0_name %in% sahelplus & reference_label == "Current: January-May")  %>%
  ggplot(aes(x = reference_year, y = phase35million)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends of the Number of Food Insecure (phase3 to phase5)", subtitle = "January - May, 2017 - 2021: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_janmay <- plot_sahel_janmay  +ylab("number of people (millions) in phase3-5") +geom_text(aes(label = round(phase35million,1), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 14)) 
#number phase3-5 current - Sep-Dec
plot_sahel_sepdec <- data_filtered %>% filter(adm0_name %in% sahelplus & reference_label == "Current: September-December")  %>%
  ggplot(aes(x = reference_year, y = phase35million)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends of the Number of Food Insecure (phase3 to phase5)", subtitle = "September - December, 2017 - 2020: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_sepdec <- plot_sahel_sepdec  +ylab("number of people (millions) in phase3-5") +geom_text(aes(label = round(phase35million,1), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 14)) 
#number of pop by phase - simple 
plot_sahel_phase_proj <- data_filtered_country %>% filter(adm0_name %in% sahelplus & reference_label == "Projected: June-August") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ adm0_name) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year and Country", subtitle = "June - August, 2017 - 2021, 2017 - 2020: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_phase_proj  <- plot_sahel_phase_proj +ylab("number of people (millions)")
plot_sahel_phase_janmay <- data_filtered_country %>% filter(adm0_name %in% sahelplus & reference_label == "Current: January-May") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ adm0_name) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year and Country", subtitle = "January - May, 2017 - 2021: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_phase_janmay   <- plot_sahel_phase_janmay  +ylab("number of people (millions)")
plot_sahel_phase_sepdec <- data_filtered_country %>% filter(adm0_name %in% sahelplus & reference_label == "Current: September-December") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ adm0_name) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year and Country", subtitle = "September - December, 2017 - 2021: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_phase_sepdec  <- plot_sahel_phase_sepdec +ylab("number of people (millions)")


#Coastal 
#number phase3-5 projected
plot_coastal_proj <- data_filtered %>% filter(adm0_name %in% coastal & reference_label == "Projected: June-August")  %>%
  ggplot(aes(x = reference_year, y = phase35million)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends of the Number of Food Insecure (phase3 to phase5)", subtitle = "June - August, 2017 - 2021: Coastal Countries", caption = "") 
plot_coastal_proj <- plot_coastal_proj  +ylab("number of people (millions) in phase3-5") +geom_text(aes(label = round(phase35million,2), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 2)) 
#number phase3-5 current - Jan-May
plot_coastal_janmay <- data_filtered %>% filter(adm0_name %in% coastal & reference_label == "Current: January-May")  %>%
  ggplot(aes(x = reference_year, y = phase35million)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends of the Number of Food Insecure (phase3 to phase5)", subtitle = "January - May, 2017 - 2021: Coastal Countries", caption = "") 
plot_coastal_janmay <- plot_coastal_janmay  +ylab("number of people (millions) in phase3-5") +geom_text(aes(label = round(phase35million,2), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 2)) 
#number phase3-5 current - Sep-Dec
plot_coastal_sepdec <- data_filtered %>% filter(adm0_name %in% coastal & reference_label == "Current: September-December")  %>%
  ggplot(aes(x = reference_year, y = phase35million)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends of the Number of Food Insecure (phase3 to phase5)", subtitle = "September - December, 2017 - 2020: Coastal Countries", caption = "") 
plot_coastal_sepdec <- plot_coastal_sepdec  +ylab("number of people (millions) in phase3-5") +geom_text(aes(label = round(phase35million,2), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 2)) 
#number of pop by phase - simple 
plot_coastal_phase_proj <- data_filtered_country %>% filter(adm0_name %in% coastal & reference_label == "Projected: June-August") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ adm0_name) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year and Country", subtitle = "June - August, 2017 - 2021, 2017 - 2020: Coastal countries", caption = "") 
plot_coastal_phase_proj  <- plot_coastal_phase_proj +ylab("number of people (millions)")
plot_coastal_phase_janmay <- data_filtered_country %>% filter(adm0_name %in% coastal & reference_label == "Current: January-May") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ adm0_name) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year and Country", subtitle = "January - May, 2017 - 2021: Coastal countries", caption = "") 
plot_coastal_phase_janmay   <- plot_coastal_phase_janmay  +ylab("number of people (millions)")
plot_coastal_phase_sepdec <- data_filtered_country %>% filter(adm0_name %in% coastal & reference_label == "Current: September-December") %>% ggplot(aes(x = reference_year, y = value, fill = phase)) +geom_bar(stat = "identity") +facet_grid(. ~ adm0_name) +scale_fill_manual(values = CH_colors) +theme_vamgraphs() +labs(title = "Trends of Estimated Population by Phase and Year and Country", subtitle = "September - December, 2017 - 2021: Coastal countries", caption = "") 
plot_coastal_phase_sepdec  <- plot_coastal_phase_sepdec +ylab("number of people (millions)")

#Sahel
#% phase3-5 projected
plot_sahel_proj_perc <- data_filtered %>% filter(adm0_name %in% sahelplus & reference_label == "Projected: June-August")  %>%
  ggplot(aes(x = reference_year, y = perc35)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends in the Percentage of Food Insecure (phase3 to phase5)", subtitle = "June - August, 2017 - 2021: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_proj_perc <- plot_sahel_proj_perc  +ylab("percent of people in phase3-5") +geom_text(aes(label = round(perc35), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 60)) 
#% phase3-5 current - Jan-May
plot_sahel_janmay_perc <- data_filtered %>% filter(adm0_name %in% sahelplus & reference_label == "Current: January-May")  %>%
  ggplot(aes(x = reference_year, y = perc35)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends in the Percentage of Food Insecure (phase3 to phase5)", subtitle = "January - May, 2017 - 2021: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_janmay_perc <- plot_sahel_janmay_perc  +ylab("percent of people in phase3-5") +geom_text(aes(label = round(perc35), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 60)) 
#% phase3-5 current - Sep-Dec
plot_sahel_sepdec_perc <- data_filtered %>% filter(adm0_name %in% sahelplus & reference_label == "Current: September-December")  %>%
  ggplot(aes(x = reference_year, y = perc35)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends in the Percentage of Food Insecure (phase3 to phase5)", subtitle = "September - December, 2017 - 2020: Sahel5 +1 & CMR/CAF/NGA", caption = "") 
plot_sahel_sepdec_perc <- plot_sahel_sepdec_perc +ylab("percent of people in phase3-5") +geom_text(aes(label = round(perc35), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 60)) 

#Coastal 
# % phase3-5 projected
plot_coastal_proj_perc <- data_filtered %>% filter(adm0_name %in% coastal & reference_label == "Projected: June-August")  %>%
  ggplot(aes(x = reference_year, y = perc35)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends in the Percentage of Food Insecure (phase3 to phase5)", subtitle = "June - August, 2017 - 2021: Coastal countries", caption = "") 
plot_coastal_proj_perc  <- plot_coastal_proj_perc   +ylab("percent of people in phase3-5") +geom_text(aes(label = round(perc35), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 20)) 
# % phase3-5 current - Jan-May
plot_coastal_janmay_perc <- data_filtered %>% filter(adm0_name %in% coastal & reference_label == "Current: January-May")  %>%
  ggplot(aes(x = reference_year, y = perc35)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends in the Percentage of Food Insecure (phase3 to phase5)", subtitle = "January - May, 2017 - 2021: Coastal countries", caption = "") 
plot_coastal_janmay_perc <- plot_coastal_janmay_perc +ylab("percent of people in phase3-5") +geom_text(aes(label = round(perc35), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 20)) 
# % phase3-5 current - Sep-Dec
plot_coastal_sepdec_perc <- data_filtered %>% filter(adm0_name %in% coastal & reference_label == "Current: September-December")  %>%
  ggplot(aes(x = reference_year, y = perc35)) +geom_col(position = "dodge",fill = "#4E84C4", width = .75) +facet_grid(. ~ adm0_name) +theme_vamgraphs() +labs(title = "Trends in the Percentage of Food Insecure (phase3 to phase5)", subtitle = "September - December, 2017 - 2020: Coastal countries", caption = "") 
plot_coastal_sepdec_perc <- plot_coastal_sepdec_perc  +ylab("percent of people in phase3-5") +geom_text(aes(label = round(perc35), angle = 90, vjust = .5, hjust = -.1), size = 3) +scale_y_continuous(limits = c(0, 20)) 
```

```{r}
plot_rbd_35
```

```{r}
plot_rbd_janmay
```

```{r}
plot_rbd_proj
```

```{r}
plot_rbd_sepdec
```

```{r}
plot_rbd_janmay_fac
```

```{r}
plot_rbd_proj_fac
```

```{r}
plot_rbd_sepdec_fac
```

```{r}
plot_sahel_janmay
```

```{r}
plot_sahel_proj
```

```{r}
plot_sahel_sepdec
```

```{r}
plot_coastal_janmay
```

```{r}
plot_coastal_proj
```

```{r}
plot_coastal_sepdec
```

```{r}
plot_sahel_janmay_perc
```

```{r}
plot_sahel_proj_perc
```

```{r}
plot_sahel_sepdec_perc
```

```{r}
plot_coastal_janmay_perc
```

```{r}
plot_coastal_proj_perc
```

```{r}
plot_coastal_sepdec_perc
```

```{r}
plot_sahel_phase_janmay
```

```{r}
plot_sahel_phase_proj
```

```{r}
plot_sahel_phase_sepdec
```

```{r}
plot_coastal_phase_janmay
```

```{r}
plot_coastal_phase_proj
```

```{r}
plot_coastal_phase_sepdec
```





